### ISSUE TITLE
when load RFJModel class asynchronized, app crash

### ISSUE THREAD

**Issue by 535017742** [refusebt/RFJModel#1]
RFJModel class has a method named initialize. but the implemention of it has a single instance namely modelInfos. when system call RFJModel's initialize method at the same time asynchronized, it will crash at initialize method.  

中文：RFJModel类的initialize方法的实现中用到了一个单例，当app异步同时调用initialize方法时发生了数据共享导致执行时crash. 正确解法应该是给代码[[RFJModel modelInfos] setObject:mapPropertyInfos forKey:[NSValue valueWithPointer:className]]; 加锁。望尽快修复~~

**Comment by refusebt** [comment]
试试 branch “Issue_1”
